### ISSUE TITLE
we need a new name for this project

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/sandcastle#2]
so, it's not a generator, it runs commands in a sandbox where the implementation is openshift now (which is possible that it would change in the future)

Ideas:
* sandcastle - funnily enough, there is already a [sandcastle](https://github.com/bcoe/sandcastle) project which is also a sandbox

**Comment by phracek** [comment]
- `sandpackit_generator` - sand for generation sources by packit
- `sandpackit` - sand for packit. You will not destroy packite-service at all.
- `packitcastle` - you can do everething in packit castle. We are still running, though
- `packitground` - ground for your packit place.
- `sandground` - ground where you can do everything, but packit-service is still alive.

@jpopelka @dhodovsk @eliskasl Please write down a proposal.
It is gonna be a long term issue for the proper name:P

**Comment by jpopelka** [comment]
`sandcastle` +1

**Comment by phracek** [comment]
sandcastle +1
