### ISSUE TITLE
Add python2 to build EPEL 6 and 7 SRPMs

### ISSUE THREAD

**Issue by bocekm** [packit-service/sandcastle#49]
I've got a package distributed in EPEL 6 and 7 and it's written for python2.

What I've got in the [.packit.yml](https://github.com/bocekm/convert2rhel/blob/use_packit/.packit.yaml) is:
`create_tarball_command: ["python2", "setup.py", "sdist", "--dist-dir", "."]`

which fails on building SRPM in the sandcastle:
```
Preparing of the upstream to the SRPM build failed: Command failed (rc=127, reason={"metadata":{},"status":"Failure","message":"command terminated with non-zero exit code: Error executing in Docker Container: 127","reason":"NonZeroExitCode","details":{"causes":[{"reason":"ExitCode","message":"127"}]}})
/sandcastle/script.sh: line 3: exec: python2: not found
```

Related:
https://github.com/oamg/convert2rhel/pull/11

**Comment by TomasTomecek** [comment]
I hope that python2 and python2-setuptools should be enough
