### ISSUE TITLE
modulemd - missing C deps

### ISSUE THREAD

**Issue by dhodovsk** [packit-service/sandcastle#52]
Related PR - https://github.com/fedora-modularity/libmodulemd/pull/433/
From what I've tried, these were needed:
 - gtk-doc
 - rpm-devel
 - glib
 - glib2-devel
 - glib2-doc
 - libyaml-devel
 - ghc-magic-devel

There were some more needed, but I got stuck at:
```
[root@d25f2d34548f libmodulemd]# ./.make_packit_specfile.sh 
The Meson build system
Version: 0.52.0
Source dir: /src/libmodulemd
Build dir: /src/libmodulemd/packit
Build type: native build
Project name: modulemd
Project version: 2.9.0
C compiler for the host machine: ccache cc (gcc 9.2.1 "cc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)")
C linker for the host machine: GNU ld.bfd 2.31.1-37
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Werror=missing-declarations: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wuninitialized: YES 
Compiler for C supports arguments -Werror=format-security -Werror=format=2: YES 
Compiler for C supports arguments -Werror=implicit: YES 
Compiler for C supports arguments -Werror=init-self: YES 
Compiler for C supports arguments -Werror=main: YES 
Compiler for C supports arguments -Werror=missing-braces: YES 
Compiler for C supports arguments -Werror=return-type: YES 
Compiler for C supports arguments -Werror=array-bounds: YES 
Compiler for C supports arguments -Werror=write-strings: YES 
Compiler for C supports arguments -D_GNU_SOURCE: YES 
Compiler for C supports arguments -DG_LOG_USE_STRUCTURED: YES 
Compiler for C supports arguments -DG_LOG_DOMAIN="libmodulemd": YES 
Found pkg-config: /usr/bin/pkg-config (1.6.1)
Run-time dependency gobject-2.0 found: YES 2.60.7
Run-time dependency yaml-0.1 found: YES 0.2.1
Run-time dependency rpm found: YES 4.14.2.1
Library magic found: YES
Run-time dependency glib-2.0 found: YES 2.60.7
Program sh found: YES (/usr/bin/sh)
Program sed found: YES (/usr/bin/sed)
Program test found: YES (/usr/bin/test)
Run-time dependency gtk-doc found: YES 1.29

meson.build:76:4: ERROR: Problem encountered: Missing documentation for GLib.
```

**Comment by TomasTomecek** [comment]
> Missing documentation for GLib.

Why the F would we need documentation to create an archive -_-

**Comment by sgallagher** [comment]
@dhodovsk @TomasTomecek 

We don't actually need the documentation just to create the archive. Probably best to pass `-Dwith_docs=False` to the meson command.

(For the record, the reason it's failing is because `dnf` in containers passes `tsflags=nodocs`, which is why `glib2-docs` is not satisfying the requirement.)

What is the appropriate mechanism for installing the dependencies for packit? Explicitly install them as part of the `./.make_packit_specfile.sh`? Or should I add a `-Darchive_only=True` option to the project to skip checking the dependencies if we are only trying to create the archive?

**Comment by sgallagher** [comment]
In more detail: when generating an archive with `meson`, we first need to generate a build directory (equivalent to running `./configure` on an autotools project).

**Comment by sgallagher** [comment]
> @dhodovsk @TomasTomecek
> What is the appropriate mechanism for installing the dependencies for packit? Explicitly install them as part of the `./.make_packit_specfile.sh`? Or should I add a `-Darchive_only=True` option to the project to skip checking the dependencies if we are only trying to create the archive?

Well, I apparently can't run `sudo yum install` inside this script, since the Packit user apparently doesn't have that privilege. Is there a configuration option I'm missing to let me specify deps needed for the setup?

**Comment by TomasTomecek** [comment]
Yup, the sandbox environment is an openshift pod, so no root :/ We're installing dependencies ad-hoc. 

I took all the packages you listed, installed them and tried locally and sadly got the same error. But luckily the meson-log.txt contained the real problem:
```
Run-time dependency gtk-doc found: YES 1.29

meson.build:76:4: ERROR: Problem encountered: Missing documentation for GLib.

A full log can be found at /libmodulemd/packit/meson-logs/meson-log.txt
STDERR: sudo: setrlimit(RLIMIT_CORE): Operation not permitted
ERROR    Command ['./.make_packit_specfile.sh'] failed
ERROR    Command ['./.make_packit_specfile.sh'] failed.
ERROR    Command ['./.make_packit_specfile.sh'] failed: Command ['./.make_packit_specfile.sh'] failed.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/packit/cli/utils.py", line 61, in covered_func
    func(config=config, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/packit/cli/srpm.py", line 75, in srpm
    srpm_path = api.create_srpm(output_file=output, upstream_ref=upstream_ref)
  File "/usr/lib/python3.7/site-packages/packit/api.py", line 452, in create_srpm
    self.up.run_action(actions=ActionName.post_upstream_clone)
  File "/usr/lib/python3.7/site-packages/packit/base_git.py", line 214, in run_action
    if self.with_action(action=actions):
  File "/usr/lib/python3.7/site-packages/packit/base_git.py", line 257, in with_action
    self.command_handler.run_command(command=command_l, env=env)
  File "/usr/lib/python3.7/site-packages/packit/command_handler.py", line 68, in run_command
    env=env,
  File "/usr/lib/python3.7/site-packages/packit/utils.py", line 105, in run_command
    raise PackitException(f"Command {shell.args!r} failed: {error_message}")
packit.exceptions.PackitException: Command ['./.make_packit_specfile.sh'] failed: Command ['./.make_packit_specfile.sh'] failed.

[root@a397c1b51665 libmodulemd]# rpm -q glib2-doc
glib2-doc-2.60.7-2.fc30.noarch
```

I'd say that the real problem is: `STDERR: sudo: setrlimit(RLIMIT_CORE): Operation not permitted
`

I'd like to apologize about my original F comment - I lost my temper (because I did not understand the error message - I thought that meson needs documentation in order to run, not that it needs to generate documentation).

**Comment by sgallagher** [comment]
Not a problem. That `sudo` is actually new; I just added it to see if I could install dependencies into the pod. I'm going to see if I can just bypass meson (and its dependency checks) to generate the tarball and spec file.

**Comment by TomasTomecek** [comment]
@sgallagher oki, let us know if you need help with plugging it into packit

**Comment by sgallagher** [comment]
@TomasTomecek I've managed to bypass meson, but now I'm getting a different error (with insufficient logs to figure out what's wrong): https://github.com/fedora-modularity/libmodulemd/pull/433#issuecomment-580251156

**Comment by dhodovsk** [comment]
The `specfile_path` in packit config points to `packit/libmodulemd.spec`. But the `.make_packit_specfile.sh` seems to create the spec next to libmodulemd.spec.in in git root dir.

**Comment by sgallagher** [comment]
@dhodovsk Thanks, that was it. Things seem to be working fine now. You can probably close this; we don't need to pollute the build environment with my dependencies.

**Comment by TomasTomecek** [comment]
closing per Stephen's request :)
