### ISSUE TITLE
Stable branch to create :prod image

### ISSUE THREAD

**Issue by jpopelka** [packit-service/sandcastle#66]
At the moment we use `:latest` in both `stg`/`prod`.
It'd be nice to have different branch/image for `prod` so that we don't accidentally break it with untested change.

Update also [deployment README](https://github.com/packit-service/deployment#prod-re-deployment) & [deployment/cron-jobs/import-images/import-images.sh](https://github.com/packit-service/deployment/blob/master/cron-jobs/import-images/import-images.sh)

**Comment by jpopelka** [comment]
Also, to let the service know which image to use you AFAIK have to set in in [packit-service.yaml](https://github.com/packit-service/deployment/blob/master/secrets/template/packit-service.yaml#L27) for each deployment.

**Comment by TomasTomecek** [comment]
@jpopelka @lbarcziova is this done now?

**Comment by lbarcziova** [comment]
@TomasTomecek yes, it's done
